import { type FormEvent, useState } from 'react'
import { NumberField } from '../components/NumberField'
import { ResultPanel } from '../components/ResultPanel'
import { StairPreview } from '../components/StairPreview'
import { analyzeStraightStair, downloadStraightStairDxf } from '../services/api'
import type { StraightStairAnalysis, StraightStairRequest } from '../types/stair'

const initialInput:StraightStairRequest={lowerBeamWidthCm:20,lowerBeamHeightCm:50,lowerLandingLengthCm:80,upperBeamWidthCm:20,upperBeamHeightCm:50,upperLandingLengthCm:100,stairWidthCm:120,treadCm:30,riserCm:18,riserCount:10,waistThicknessCm:15,concreteStrengthMpa:20,liveLoadKnM2:3,coverCm:2.5,mainBarDiameterMm:6.3,distributionBarDiameterMm:5,aggregate:'Basalt',support:'SimplySupported'}

export function StraightStairPage(){
  const[input,setInput]=useState(initialInput);const[result,setResult]=useState<StraightStairAnalysis|null>(null);const[loading,setLoading]=useState(false);const[downloading,setDownloading]=useState(false);const[error,setError]=useState('')
  const updateNumber=(name:string,value:number)=>{setInput(current=>({...current,[name]:value}));setResult(null)}
  const analyze=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError('');try{setResult(await analyzeStraightStair(input))}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível calcular a escada.')}finally{setLoading(false)}}
  const downloadDxf=async()=>{setDownloading(true);setError('');try{await downloadStraightStairDxf(input)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível gerar o DXF.')}finally{setDownloading(false)}}
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#top" aria-label="WebCivil, página inicial"><img src="/logo.png" alt="WebCivil Apps de Engenharia"/></a><nav aria-label="Navegação principal"><a className="active" href="#dimensionamento">Escadas</a><a href="#resultados">Resultados</a></nav><div className="project-badge"><span/> Projeto sem título</div></header>
    <main id="top">
      <section className="hero"><div><span className="eyebrow">Concreto armado · Escada de um lance</span><h1>Dimensione a escada e gere o detalhamento em DXF.</h1><p>Informe a geometria, os materiais e os apoios. O WebCivil calcula os esforços e entrega um arquivo CAD estruturado em camadas.</p></div><div className="hero-step"><strong>01</strong><span>Primeiro módulo migrado<br/>do AutoPliss</span></div></section>
      <form id="dimensionamento" onSubmit={analyze}><div className="workspace"><div className="form-column">
        <section className="form-card"><div className="section-title"><div><span className="step-number">01</span><h2>Geometria da escada</h2></div><span className="section-hint">Medidas em centímetros</span></div><div className="field-grid three">
          <NumberField label="Largura da escada" name="stairWidthCm" value={input.stairWidthCm} unit="cm" min={40} onChange={updateNumber}/><NumberField label="Piso" name="treadCm" value={input.treadCm} unit="cm" min={10} onChange={updateNumber}/><NumberField label="Espelho" name="riserCm" value={input.riserCm} unit="cm" min={5} step={.5} onChange={updateNumber}/><NumberField label="Quantidade de espelhos" name="riserCount" value={input.riserCount} min={2} onChange={updateNumber}/><NumberField label="Espessura da laje" name="waistThicknessCm" value={input.waistThicknessCm} unit="cm" min={7} step={.5} onChange={updateNumber}/><NumberField label="Cobrimento nominal" name="coverCm" value={input.coverCm} unit="cm" min={1} step={.5} onChange={updateNumber}/>
        </div></section>
        <section className="form-card"><div className="section-title"><div><span className="step-number">02</span><h2>Patamares e vigas</h2></div></div><div className="subsection"><h3>Apoio inferior</h3><div className="field-grid three"><NumberField label="Comprimento do patamar" name="lowerLandingLengthCm" value={input.lowerLandingLengthCm} unit="cm" min={0} onChange={updateNumber}/><NumberField label="Largura da viga" name="lowerBeamWidthCm" value={input.lowerBeamWidthCm} unit="cm" min={1} onChange={updateNumber}/><NumberField label="Altura da viga" name="lowerBeamHeightCm" value={input.lowerBeamHeightCm} unit="cm" min={1} onChange={updateNumber}/></div></div><div className="subsection"><h3>Apoio superior</h3><div className="field-grid three"><NumberField label="Comprimento do patamar" name="upperLandingLengthCm" value={input.upperLandingLengthCm} unit="cm" min={0} onChange={updateNumber}/><NumberField label="Largura da viga" name="upperBeamWidthCm" value={input.upperBeamWidthCm} unit="cm" min={1} onChange={updateNumber}/><NumberField label="Altura da viga" name="upperBeamHeightCm" value={input.upperBeamHeightCm} unit="cm" min={1} onChange={updateNumber}/></div></div></section>
        <section className="form-card"><div className="section-title"><div><span className="step-number">03</span><h2>Materiais e modelo</h2></div></div><div className="field-grid three"><NumberField label="fck" name="concreteStrengthMpa" value={input.concreteStrengthMpa} unit="MPa" min={20} max={50} step={5} onChange={updateNumber}/><NumberField label="Carga acidental" name="liveLoadKnM2" value={input.liveLoadKnM2} unit="kN/m²" min={0} step={.5} onChange={updateNumber}/><label className="field"><span>Agregado graúdo</span><select value={input.aggregate} onChange={event=>{setInput({...input,aggregate:event.target.value as StraightStairRequest['aggregate']});setResult(null)}}><option value="Basalt">Basalto / diabásio</option><option value="Granite">Granito / gnaisse</option><option value="Limestone">Calcário</option><option value="Sandstone">Arenito</option></select></label><NumberField label="Bitola principal" name="mainBarDiameterMm" value={input.mainBarDiameterMm} unit="mm" min={4} step={.1} onChange={updateNumber}/><NumberField label="Bitola de distribuição" name="distributionBarDiameterMm" value={input.distributionBarDiameterMm} unit="mm" min={4} step={.1} onChange={updateNumber}/><label className="field"><span>Condição de apoio</span><select value={input.support} onChange={event=>{setInput({...input,support:event.target.value as StraightStairRequest['support']});setResult(null)}}><option value="SimplySupported">Biapoiada</option><option value="FixedBothEnds">Biengastada</option></select></label></div></section>
      </div><aside className="side-column"><StairPreview input={input}/><div className="action-card"><div><span className="eyebrow">Pronto para processar</span><h2>Calcular escada</h2><p>O cálculo reproduz a formulação estrutural do AutoPliss para a faixa de 1 metro.</p></div>{error&&<div className="error" role="alert">{error}</div>}<button className="button primary" type="submit" disabled={loading}>{loading?'Calculando…':'Calcular dimensionamento'} <span>→</span></button><button className="button secondary" type="button" onClick={downloadDxf} disabled={downloading}>{downloading?'Gerando DXF…':'Baixar detalhamento DXF'} <span>↓</span></button><small className="privacy">O DXF é gerado diretamente pela API, sem comandos de área de transferência.</small></div></aside></div></form>
      <div id="resultados">{result&&<ResultPanel result={result}/>}</div>
    </main><footer><span>WebCivil · Apps de Engenharia</span><span>Módulo Escadas v0.1</span></footer>
  </div>
}
